# Generated by Django 5.0.1 on 2024-10-17 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meta', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='membershipdetail',
            name='days',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='membershipdetail',
            name='identity',
            field=models.CharField(choices=[('annually', 'Annually'), ('half_yearly', 'Half Yearly'), ('quarterly', 'Quarterly'), ('not_selected', 'Not Selected')], default='not_selected', max_length=512, unique=True),
        ),
    ]
