# Generated by Django 5.1.4 on 2024-12-28 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meta', '0002_membershipdetail_days_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={'default_related_name': 'related_cities', 'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='country',
            options={'default_related_name': 'related_countries', 'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='state',
            options={'default_related_name': 'related_states', 'ordering': ['-created_at']},
        ),
        migrations.RenameField(
            model_name='city',
            old_name='created',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='city',
            old_name='modified',
            new_name='modified_at',
        ),
        migrations.RenameField(
            model_name='country',
            old_name='created',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='country',
            old_name='modified',
            new_name='modified_at',
        ),
        migrations.RenameField(
            model_name='state',
            old_name='created',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='state',
            old_name='modified',
            new_name='modified_at',
        ),
        migrations.RemoveField(
            model_name='city',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='city',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='city',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='country',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='country',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='country',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='state',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='state',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='state',
            name='is_deleted',
        ),
        migrations.DeleteModel(
            name='MembershipDetail',
        ),
    ]
