# Generated by Django 5.1.4 on 2024-12-29 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acess', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('buyers', 'Buyers')], default='buyers', max_length=512),
        ),
    ]
