# Generated by Django 5.1.4 on 2024-12-29 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('acess', '0002_alter_user_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
    ]
