# Generated by Django 5.1.4 on 2024-12-29 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acess', '0003_remove_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, default=None, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(blank=True, default=None, max_length=512, null=True),
        ),
    ]
