# Generated by Django 5.1.4 on 2025-01-06 11:59

import apps.common.model_fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('acess', '0007_alter_user_managers'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=apps.common.model_fields.AppPhoneNumberField(blank=True, default=None, max_length=128, null=True, region=None, unique=True),
        ),
    ]
