# Generated by Django 5.1.4 on 2024-12-30 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_category_deleted_at_category_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcategory',
            name='deleted_at',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
