# Generated by Django 5.1.4 on 2024-12-31 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_product_offer_image_specification'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='avalilable_stock',
            new_name='available_stock',
        ),
    ]
