# Generated by Django 5.1.4 on 2024-12-31 11:50

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_rename_avalilable_stock_product_available_stock'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='specification',
            options={'default_related_name': 'related_Specification'},
        ),
        migrations.RemoveField(
            model_name='specification',
            name='product',
        ),
        migrations.RemoveField(
            model_name='specification',
            name='value',
        ),
        migrations.AddField(
            model_name='specification',
            name='sub_category',
            field=models.ForeignKey(default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, to='inventory.subcategory'),
            preserve_default=False,
        ),
    ]
