# Generated by Django 5.1.4 on 2024-12-31 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_alter_specification_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='specification',
            name='sub_category',
        ),
    ]
