# Generated by Django 5.1.4 on 2024-12-31 11:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_remove_specification_sub_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='specification',
            name='sub_category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='inventory.subcategory'),
            preserve_default=False,
        ),
    ]
