# Generated by Django 5.1.4 on 2025-01-01 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_alter_category_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='category',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='subcategory',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='subcategory',
            name='is_deleted',
        ),
    ]
