# Generated by Django 5.1.4 on 2025-01-01 16:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0014_remove_specification_key_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='specification',
            name='key',
            field=models.CharField(default=None, max_length=512),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='specification',
            name='sub_category',
            field=models.ForeignKey(default=10, on_delete=django.db.models.deletion.CASCADE, to='inventory.subcategory'),
            preserve_default=False,
        ),
    ]
