# Generated by Django 5.1.4 on 2025-01-02 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0016_productspecification'),
    ]

    operations = [
        migrations.AddField(
            model_name='productspecification',
            name='Value',
            field=models.CharField(default=None, max_length=512),
            preserve_default=False,
        ),
    ]
