# Generated by Django 5.1.4 on 2025-01-02 05:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0017_productspecification_value'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productspecification',
            old_name='Value',
            new_name='value',
        ),
    ]
