# Generated by Django 5.1.4 on 2025-01-06 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0029_remove_order_final_price_alter_order_total_discount'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subcategory',
            options={'default_related_name': 'related_sub_categories'},
        ),
    ]
