# Generated by Django 5.1.4 on 2025-01-07 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0032_alter_order_razorpay_order_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='razorpay_order_id',
        ),
    ]
