# Generated by Django 5.1.4 on 2025-01-08 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0034_orderitem_delete_ordertracking'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='product',
        ),
    ]
