# Generated by Django 5.1.4 on 2025-01-08 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0036_orderitem_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='product',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='user',
        ),
    ]
