# Generated by Django 5.1.4 on 2025-01-08 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0039_orderitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ratingreview',
            name='order',
        ),
    ]
