# Generated by Django 5.1.4 on 2025-01-15 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0040_remove_ratingreview_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='discount_value',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='offer',
            name='terms_and_conditions',
            field=models.TextField(blank=True, default=None, max_length=512, null=True),
        ),
    ]
