# Generated by Django 5.1.4 on 2025-01-15 14:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0041_offer_discount_value_offer_terms_and_conditions'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='selected_offer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.offer'),
        ),
    ]
